name-template: "sql/v$RESOLVED_VERSION 🌈"
tag-template: "sql/v$RESOLVED_VERSION"
tag-prefix: "sql/v"
include-paths:
  - "packages/sql"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
autolabeler:
  - label: "chore"
    title:
      - "/chore/i"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "enhancement"
    title:
      - "/feature/i"
    branch:
      - '/feature\/.+/'
template: |
  ## Changes

  $CHANGES
