# deno-fmt-ignore-file
name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DENO_DIR: /tmp/.deno-cache

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      # Check if the code is formatted according to Deno's default
      # formatting conventions.
      - run: deno task ci